"""
Django settings for photo project.

Generated by 'django-admin startproject' using Django 5.1.4.
"""

import os
from pathlib import Path

# 🔑 [추가] 외부 DB 연결을 쉽게 해주는 라이브러리 임포트
import dj_database_url 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 🔑 경로 통일: Pathlib 객체를 사용하여 프로젝트 구조에 맞는 경로 정의
PROJECT_ROOT = BASE_DIR.parent.parent # /app/ (배포 환경 가정)
REACT_APP_DIR = PROJECT_ROOT / 'front' # /app/front
REACT_BUILD_DIR = REACT_APP_DIR / 'build' # /app/front/build

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-&(q+p!pj5u4_lz6#!&=b1^h(#l9pq3et7-pwk3&=r2%9ms*86r'
DEBUG = True


# Application definition
CORS_ALLOW_CREDENTIALS = True

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'catalog.apps.CatalogConfig',
    'rest_framework',
    'rest_framework.authtoken',
]

# 🔑 MIDDLEWARE 정리: 중복 제거 및 Whitenoise 고정
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ASGI_APPLICATION = 'photo.asgi.application'
ROOT_URLCONF = 'photo.urls'

# 🔑 TEMPLATES 설정: index.html 경로 정확히 지정
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [REACT_BUILD_DIR], # Pathlib 객체 사용
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'photo.wsgi.application'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Database
# 🔑 [수정된 부분] Cloud SQL 환경 변수를 사용하여 DB 연결을 설정합니다.
DATABASES = {
    'default': dj_database_url.config(
        # 환경 변수 DATABASE_URL이 없으면 로컬 개발을 위해 SQLite를 기본값으로 사용합니다.
        default=os.environ.get(
            'DATABASE_URL', 
            f'sqlite:///{BASE_DIR / "db.sqlite3"}'
        ),
        conn_max_age=600  # 연결 유지 시간 설정 (권장)
    )
}

ALLOWED_HOSTS = [
    'srh-photo.onrender.com',
    'srh-photo-d86feda25493.herokuapp.com',
    'srh-photo-sc-b1229d9be6d2.herokuapp.com',
    'spam4cut.com',
    'www.spam4cut.com',
    'localhost',
    'srh-photo-751484481725.asia-northeast3.run.app',
    '127.0.0.1',
    os.environ.get('ALLOWED_HOST', 'localhost'),
    'testserver',
]

# settings.py에 아래 설정 추가 (또는 확인)
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

# Password validation
# ... (AUTH_PASSWORD_VALIDATORS 생략)

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 🔑 STATICFILES_DIRS 정리: Pathlib 객체 사용
STATICFILES_DIRS = [
    REACT_BUILD_DIR / 'static', # JS/CSS
    REACT_APP_DIR / 'public',   # Frame images, mp3, manifest.json
]

# ❌ 불필요한 조건부 로직 삭제 (MIDDLEWARE에서 처리됨)
# if not DEBUG:
#     MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
#     STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000', 
    'http://localhost:8000',
    'http://127.0.0.1:3000',
    'https://srh-photo.onrender.com',
    'https://srh-photo-751484481725.asia-northeast3.run.app',
    "https://srh-photo-d86feda25493.herokuapp.com",
    "https://srh-photo-sc-b1229d9be6d2.herokuapp.com",
    'https://spam4cut.com',
]
# ... (CSRF_TRUSTED_ORIGINS, CORS_ALLOW_METHODS, CORS_ALLOW_HEADERS 생략) ...

# 🛡️ DATABASES 오류 안전 장치: 이 코드는 이제 불필요하거나, 위 코드가 처리합니다. 삭제 권장
# if 'default' not in DATABASES or 'ENGINE' not in DATABASES['default']:
#     DATABASES['default'] = {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }